### ISSUE TITLE
大佬救命！

### ISSUE THREAD

**Issue by nanxu2019** [kissnavel/loveMys#1]
![Image_2483241644260929](https://github.com/user-attachments/assets/ee025248-58d2-434e-bfbf-8c82599110cb)
![Image_2483229913136972](https://github.com/user-attachments/assets/d354d60a-bb01-4447-aab8-acb10a8f18bd)
要么就是一直配置不正确，折腾半天改了源码好消息有反应了，坏消息还是不可用，所以大佬可以加下好友吗807331475，再不救命真的死了，寄
![IMG_20241128_005544](https://github.com/user-attachments/assets/ec321863-03e7-4ecc-ad0a-9d95332c2021)

**Comment by nanxu2019** [comment]
修改半天，过码的后台都提示过码成功了，结果这个插件还是说遇到验证码，稍后再试
![IMG_20241128_005544](https://github.com/user-attachments/assets/c1b9a4eb-bd7f-4776-8a3c-50b14c8bc086)

**Comment by kissnavel** [comment]
> 修改半天，过码的后台都提示过码成功了，结果这个插件还是说遇到验证码，稍后再试 ![IMG_20241128_005544](https://private-user-images.githubusercontent.com/108602897/390503069-c1b9a4eb-bd7f-4776-8a3c-50b14c8bc086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODI3MzEsIm5iZiI6MTczMjc4MjQzMSwicGF0aCI6Ii8xMDg2MDI4OTcvMzkwNTAzMDY5LWMxYjlhNGViLWJkN2YtNDc3Ni04YTNjLTUwYjE0YzhiYzA4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwODI3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2FiNGEyMzIxYzQzY2Q5MTc4NjFiNDhlNDQ5Y2U3OGZiOTU1ZDU4Nzk4MTc1NGNkMjY1ZTAxYWIxNTZlMDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kX0zwTtpeZwpzlw_w4OWPglJtqHAp5v8Wknnay_Dceg)

插件原作者已经很久没跟新，我只是做了部分的功能修改，核心的过码只能等原作者修复了。
国服报验证码是因为国服fp问题，这一部分原genshin插件未更新，可待原插件更新或者使用他人修改过后的独立genshin仓库。

**Comment by nanxu2019** [comment]
那昨晚白折腾半天了[IMG_20241128_005544](https://private-user-images.githubusercontent.com/108602897/390503069-c1b9a4eb-bd7f-4776-8a3c-50b14c8bc086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3ODQxNDEsIm5iZiI6MTczMjc4Mzg0MSwicGF0aCI6Ii8xMDg2MDI4OTcvMzkwNTAzMDY5LWMxYjlhNGViLWJkN2YtNDc3Ni04YTNjLTUwYjE0YzhiYzA4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwODUwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDgwMGNhNDFiZWExZjQ4ZmRlOGZkNDY5MzBlN2FjMDg2MmFhZDEzYTRiNmI0ZTExNDA4YzkzN2VmMjUzNDJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.l3QA5IgJchJ1ncnSINs4-IaoZFKRQsakUkM91ReHz2s)

**Comment by nanxu2019** [comment]
![IMG_20241128_005544](https://github.com/user-attachments/assets/298fa704-2e21-40bf-93c9-5dd5a77a52fd)
昨晚白折腾半天了，改半天源码都说米游社接口报错……我说可能插件用不了了，我朋友还不信，不过谢谢佬了

**Comment by kissnavel** [comment]
> ![IMG_20241128_005544](https://private-user-images.githubusercontent.com/108602897/390710175-298fa704-2e21-40bf-93c9-5dd5a77a52fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NjM5NzIsIm5iZiI6MTczMzY2MzY3MiwicGF0aCI6Ii8xMDg2MDI4OTcvMzkwNzEwMTc1LTI5OGZhNzA0LTJlMjEtNDBiZi05M2M5LTVkZDVhNzdhNTJmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxMzE0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjEwNjhmODJlNDhiZGZlOTNiZDE4OGQ5NjBhY2RkYmJmZDVlY2VlMWFkY2I2NDFlNTZlYjU5ZGVjNDQyZjU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ds6N9jHOiRIXqlR1Gd71tlCC8myHyy-uaN_a96Y3AYg) 昨晚白折腾半天了，改半天源码都说米游社接口报错……我说可能插件用不了了，我朋友还不信，不过谢谢佬了

加了个id尝试修复gs的验证，因为我自用修改的genshin仓库已修复国服的fp，国服用户几乎不报验证码，所以没法测试修改，如果修改没用只能等原作者修复或好心人pr。
你之前发的日志报错图是配置文件写错了，按照那两个api的文档填对即可。
